Fix interpreter integ test
Our integration tests are failing with...

  ======================================================================
  FAIL: test_running_command
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 75, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/interpreter.py", line 35, in test_running_command
      self.assertEqual(expected, _run_prompt('--run', 'GETINFO config-file'))
  AssertionError: Lists differ: ['250-config-file=/home/atagar/Desktop/stem/test/data/torrc', '250 OK'] != []

  First list contains 2 additional elements.
  First extra element 0:
  '250-config-file=/home/atagar/Desktop/stem/test/data/torrc'

  - ['250-config-file=/home/atagar/Desktop/stem/test/data/torrc', '250 OK']
  + []

Our actual reason surfaces in tor-prompt's stderr...

  % python3.7 tor-prompt --run 'GETINFO config-file' --interface 9051
  /home/atagar/Desktop/stem/stem/interpreter/__init__.py:115: RuntimeWarning: coroutine 'BaseController.__aenter__' was never awaited
    with controller:
  /home/atagar/Desktop/stem/stem/interpreter/commands.py:366: RuntimeWarning: coroutine 'BaseController.msg' was never awaited
    output = format(str(self._controller.msg(command).raw_content()).strip(), *STANDARD_OUTPUT)
  /home/atagar/Desktop/stem/stem/interpreter/__init__.py:182: RuntimeWarning: coroutine 'BaseController.__aexit__' was never awaited
    break

The problem is that stem.connection.connect() returns asynchronous controllers,
whereas callers such as the interpreter require the class to be synchronous.
This workaround is pretty gross hackery but in the long run I expect to
completely replace the module prior to Stem 2.x.