Stacktrace when calling get_circuits()
Running the ONLINE integ target uncovered another bug...

  ======================================================================
  ERROR: test_get_circuits
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1339, in test_get_circuits
      circuits = controller.get_circuits()
    File "/home/atagar/Desktop/stem/stem/control.py", line 482, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/control.py", line 3336, in get_circuits
      circ_message = stem.socket.recv_message(io.BytesIO(stem.util.str_tools._to_unicode('650 CIRC %s\r\n' % circ)))
  TypeError: 'unicode' does not have the buffer interface