Fix python3 proc regression
Unit tests failed with python 3.x due to my recent proc changes. Caught thanks
to dmr. Stacktrace when I remove the masking catch-all is...

  ======================================================================
  ERROR: test_high_connection_count
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python3.5/unittest/mock.py", line 1157, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/util/proc.py", line 349, in test_high_connection_count
      self.assertEqual(expected, proc.connections(pid))
    File "/home/atagar/Desktop/stem/stem/util/proc.py", line 398, in connections
      div = l_dst.find(':')
  TypeError: a bytes-like object is required, not 'str'

  ----------------------------------------------------------------------