Drop test_installs_all_modules
This test checks that our setup.py includes all our modules within its packages
line. The test no longer passes, but now that we're using setuptools it's
unnecessary.

  ======================================================================
  ERROR: test_installs_all_modules
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/installation.py", line 30, in test_installs_all_modules
      modules = json.loads(re.search('packages = (\\[.*\\])', self.setup_contents).group(1).replace("'", '"'))
  AttributeError: 'NoneType' object has no attribute 'group'