Setuptools creates a dist directory
Unfortunately setuptools creates a superfluous 'dist' directory that isn't
removed with clean...

  https://github.com/pypa/setuptools/issues/1347

Working around the test failure it causes...

  ======================================================================
  FAIL: test_sdist
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 141, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 208, in result
      test.fail(self._result.msg)
  AssertionError: /home/atagar/Desktop/stem/dist already exists, maybe you manually ran 'python setup.py sdist'?