Revisions for EXTENDCIRCUIT addition
Couple minor changes:

* The EXTENDCIRCUIT integ tests fails if we don't have an internet connection.
  Making it dependent on the ONLINE testing target.

* Revising the pydocs a bit. For instance, there's no point in saying "If the
  purpose isn't provided, "general" circuits are built." when we can simply
  provide a default for the argument. ;)

However, there's still a couple mysteries...

* When I was offline I got the following stacktrace...

======================================================================
ERROR: test_extendcircuit
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 373, in test_extendcircuit
    circ_id = controller.extend_circuit(0)
  File "/home/atagar/Desktop/stem/stem/control.py", line 1109, in extend_circuit
    raise stem.socket.ProtocolError("EXTENDCIRCUIT returned unexpected response code: %s" % response.code)
ProtocolError: EXTENDCIRCUIT returned unexpected response code: 512

----------------------------------------------------------------------

  However, according to the control-spec the 512 response code is for "Syntax
  error in command argument". That doesn't make sense if we're failing because
  we lack a connection.

* Is the 'path' argument for EXTENDCIRCUIT the circuits that we build through,
  or the relays to be chosen from when building a single hop? The EXTENDCIRCUIT
  description doesn't say, which seems to me to be a weakness in the spec.