Fix test regression when ed25519 support missing
Oops, accidently commited a local hack I made while troubleshooting my openssl
bindings. This in turn broke our jenkins test runs...

  ======================================================================
  ERROR: test_inner_layer_creation
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/descriptor/hidden_service_v3.py", line 343, in test_inner_layer_creation
      IntroductionPointV3.create('1.1.1.1', 9001),
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/descriptor/hidden_service.py", line 230, in create
      raise ImportError('Introduction point creation requires the cryptography module ed25519 support')
  ImportError: Introduction point creation requires the cryptography module ed25519 support

  ----------------------------------------------------------------------