Stacktrace when calling is_running with python3
Recent change broke is_running for python3...

  ======================================================================
  ERROR: test_is_running_by_name
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/util/system.py", line 144, in test_is_running_by_name
      self.assertTrue(stem.util.system.is_running(tor_cmd) or stem.util.system.is_running('tor.real'))
    File "/home/atagar/Desktop/stem/stem/util/system.py", line 449, in is_running
      if isinstance(command, (bytes, unicode)):
  NameError: global name 'unicode' is not defined