Fix authentication test
Oops, we only exercise this line when using authentication (which isn't the
default). Our tests now pass when using the RUN_ALL target.

  ======================================================================
  ERROR: test_authenticate_general_cookie
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/require.py", line 75, in wrapped
      return func(self, *args, **kwargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 701, in wrapper
      result = loop.run_until_complete(func(*args, **kwargs))
    File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
      return future.result()
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/integ/connection/authentication.py", line 221, in test_authenticate_general_cookie
      if method in protocolinfo_response.auth_methods:
  AttributeError: 'coroutine' object has no attribute 'auth_methods'