Fix --test and --exclude-test arguments
Commit 076f89d rewrote how we parse arguments. This broke our --test and
--exclude-test arguments because there is no longer a default value in the
'args' dictionary...

  % ./run_tests.py --unit --test endpoint
  Traceback (most recent call last):
    File "./run_tests.py", line 482, in <module>
      main()
    File "./run_tests.py", line 197, in main
      args = test.arguments.Arguments.parse(sys.argv[1:])
    File "/home/atagar/Desktop/stem/test/arguments.py", line 109, in parse
      args['specific_test'].append(crop_module_name(arg))
  KeyError: 'specific_test'

Reported by teor on...

  https://github.com/torproject/stem/issues/63