Tests errored with a '--log' argument
Oops, I removed our LogBuffer in commit 76b6b49 but it's still used by
run_tests.py when we have a '--log' argument. Caught thanks to our Jenkins
tests...

  Traceback (most recent call last):
    File "./run_tests.py", line 478, in <module>
      main()
    File "./run_tests.py", line 238, in main
      handler = logging_buffer = stem.util.log.LogBuffer(args.logging_runlevel)
  AttributeError: module 'stem.util.log' has no attribute 'LogBuffer'