Only use directory mirrors with a DirPort
Oops! Iirc the V2Dir flag once was only granted to relays with a DirPort but
seems that's no longer the case. As a result our use_directory_mirrors() method
inserted endpoints with port values of 'None'...

  https://trac.torproject.org/projects/tor/ticket/28393

  Traceback (most recent call last):
    File "bushel.py", line 21, in <module>
      for desc in downloader.get_consensus().run():
    ...
    File "/usr/lib/python3/dist-packages/stem/__init__.py", line 571, in __init__
      raise ValueError("'%s' isn't a valid port" % port)
  ValueError: 'None' isn't a valid port

We could use their ORPort to download descriptors instead, but Stem's ORPort
capabilities are still pretty immature so just gonna restrict ourselves to
DirPort mirrors for now instead.