Unit test python3 regression
Huh. Guess I don't test via python3 much. Commit 5488849 changed our annotation
values to unicode. Unsure that was intentional in that commit but I think
that's preferable so adjusting our tests.

  ======================================================================
  FAIL: test_annotations
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python3.5/unittest/mock.py", line 1157, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/server_descriptor.py", line 739, in test_annotations
      self.assertEqual(b'@pepperjack very tasty', desc.get_annotation_lines()[0])
  AssertionError: b'@pepperjack very tasty' != '@pepperjack very tasty'

  ----------------------------------------------------------------------