Fix multiprocessing w/ `spawn` & top level imports
This fixes `test_fibonacci_multiprocessing` on MacOS (darwin), which was
failing with:

  _pickle.PicklingError: Can't pickle <function rebuild_connection at ...>:
    import of module 'multiprocessing.connection' failed

This is due to the fact that multiprocessing on darwin defaults with the
start method of `spawn`, instead of `fork` in other POSIX environments.

- The only start method supported by all platforms is 'spawn'; moreover,
  the default method will move away from 'fork' in python 3.14. We thus
  set method='spawn' for consistency across platforms.

- `fibonacci_multiprocessing` makes use of the multiprocessing helper
  `stem.util.system.DaemonTask`, whose arguments must be imported at
  the top level for it to be properly pickled and spawned.

See: https://docs.python.org/3/library/multiprocessing.html