Fix collector integ test
Minor fix for three online tests...

  ======================================================================
  FAIL: test_index_plaintext
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 43, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/descriptor/collector.py", line 22, in test_index_plaintext
      self._test_index(None)
    File "/home/atagar/Desktop/stem/test/integ/descriptor/collector.py", line 98, in _test_index
      self.assertEqual(['archive', 'contrib', 'recent'], [entry['path'] for entry in index['directories']])
  AssertionError: Lists differ: ['archive', 'contrib', 'recent... != [u'archive', u'recent']

  First differing element 1:
  'contrib'
  u'recent'

  First list contains 1 additional elements.
  First extra element 2:
  'recent'

  - ['archive', 'contrib', 'recent']
  ?             ^^^^^^^^^^^

  + [u'archive', u'recent']
  ?  +           ^