Enumerate files when unable to find site-packages
Closer, but Jenkins evidently installs to a different path. We need to adjust
our glob pattern but first I need to expand this failure message so we know
what it should be.

  ======================================================================
  FAIL: test_install
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 141, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 208, in result
      test.fail(self._result.msg)
  AssertionError: We should only have a single site-packages directory, but instead had: []

  ----------------------------------------------------------------------