Revert "Include the originating stacktrace in stem.descriptor.remote exceptions"
Unfortunately in this case the cure is worse than the disease. When dannenberg
went down this caused stacktraces in DocTor's emails which gives the impression
the service is having problems...

  ERROR: Unable to retrieve the consensus from dannenberg (http://193.23.244.244:80/tor/status-vote/current/consensus): <urlopen error <urlopen error [Errno 111] Connection refused>

  Original traceback:
    File "/srv/doctor.torproject.org/doctor/stem/descriptor/remote.py", line 594, in _download_descriptors
      self.content, self.reply_headers = _download_from_dirport(self.download_url, self.compression, timeout)
    File "/srv/doctor.torproject.org/doctor/stem/descriptor/remote.py", line 1043, in _download_from_dirport
      timeout = timeout,
    File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/lib/python2.7/urllib2.py", line 429, in open
      response = self._open(req, data)
    File "/usr/lib/python2.7/urllib2.py", line 447, in _open
      '_open', req)
    File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
      result = func(*args)
    File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
      return self.do_open(httplib.HTTPConnection, req)
    File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
      raise URLError(err)
  URLError: <urlopen error [Errno 111] Connection refused>

I'm kinda torn on this change. On one hand it's usful information for unusual
errors, but on the other it's troubling looking bloat for mundane things like
this.

Encoding a stacktrace within an encepiton message was definitely an icky hack
so simply reverting this for now. Most likely we'll simply need to live without
underlying stacktraces until we drop python 2.x support.

This reverts commit cc43a6ca90e3943a542258b2b4d8466ae9a4ac36.