Integ regression in test_established
Damn me. Focused on the unit tests and completely forgot to check that I didn't
bork our integ tests. Caught thanks to Jenkins.

  ======================================================================
  FAIL: test_established
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/integ/client/connection.py", line 66, in test_established
      self.assertEqual(5, conn.link_protocol)
  AssertionError: 5 != LinkProtocol(version=5, circ_id_size=<stem.client.datatype.Size object at 0x7faa0199c090>, fixed_cell_len=514, first_circ_id=2147483648)