Python3 compatability for networkstatus unit test
Trivial fix. Just some missing unicode/bytes normalization.

  ======================================================================
  ERROR: test_signature_validation
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/networkstatus/document_v3.py", line 421, in test_signature_validation
      consensus = stem.descriptor.networkstatus.NetworkStatusDocumentV3(consensus_content.replace('test002r', 'different_nickname'))
  TypeError: expected an object with the buffer interface

  ----------------------------------------------------------------------