BandwidthFile python 3.x regression
Oops, forgot to re-run tests with python 3.x. Recent change had a bytes/unicode
regression slip in...

  https://trac.torproject.org/projects/tor/ticket/29332

  ======================================================================
  ERROR: test_format_v1_2
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/bandwidth_file.py", line 103, in test_format_v1_2
      self.assertEqual('1.2.0', desc.version)
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 1041, in __getattr__
      parsing_function(self, self._entries)
    File "/home/atagar/Desktop/stem/stem/descriptor/bandwidth_file.py", line 116, in _parse_header
      elif not header and 'node_id=' in line:
  TypeError: a bytes-like object is required, not 'str'