Fixing python3 issue related to unicode exit policies
Our recent exit policy caching caused a regression under python3...

Traceback (most recent call last):
  File "./test/data/python3/run_tests.py", line 25, in <module>
    import test.runner
  File "/home/atagar/Desktop/stem/test/data/python3/test/runner.py", line 51, in <module>
    import stem.connection
  File "/home/atagar/Desktop/stem/test/data/python3/stem/connection.py", line 109, in <module>
    import stem.control
  File "/home/atagar/Desktop/stem/test/data/python3/stem/control.py", line 145, in <module>
    import stem.descriptor.microdescriptor
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/__init__.py", line 546, in <module>
    import stem.descriptor.server_descriptor
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/server_descriptor.py", line 91, in <module>
    REJECT_ALL_POLICY = stem.exit_policy.ExitPolicy("reject *:*")
  File "/home/atagar/Desktop/stem/test/data/python3/stem/exit_policy.py", line 164, in __init__
    self._input_rules = zlib.compress(','.join(rules))
TypeError: 'str' does not support the buffer interface