Python3 errors due to list modificaion during iteration
When iterating over keys python 2.x makes a shallow clone of lists whereas
python 3.x doesn't. Good for performance, but means we need to be careful about
modifying a list during iteration. Caught thanks to our integ tests...

  ======================================================================
  ERROR: test_without_ephemeral_hidden_services
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 560, in test_without_ephemeral_hidden_services
      self.assertEqual([], controller.list_ephemeral_hidden_services())
    File "/home/atagar/Desktop/stem/stem/control.py", line 475, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2774, in list_ephemeral_hidden_services
      result += self.get_info('onions/current').split('\n')
    File "/home/atagar/Desktop/stem/stem/control.py", line 475, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/control.py", line 1191, in get_info
      self._set_cache(to_cache, 'getinfo')
    File "/home/atagar/Desktop/stem/stem/control.py", line 3112, in _set_cache
      for cache_key in self._request_cache.keys():
  RuntimeError: dictionary changed size during iteration