Better output for failing connection tests
Presently a test for sockstat is failing on our jenkins automated tests. This
isn't a fix for that, but this does fix the failure handling which is masking
the issue...

  ======================================================================
  ERROR: test_connections_by_sockstat
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/integ/util/connection.py", line 51, in test_connections_by_sockstat
      self.check_resolver(Resolver.SOCKSTAT)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/integ/util/connection.py", line 33, in check_resolver
      self.fail('Unable to find localhost connection with %s:\n%s' % (resolver, '\n'.join(connections)))
  TypeError: sequence item 0: expected string, Connection found