Fixing /info for python3
On irc zoltan reported that the /info command balks under python3...

  >>> /info moria1
  Traceback (most recent call last):
    File "/usr/local/bin/tor-prompt", line 8, in <module>
      stem.interpreter.main()
    File "/usr/local/lib/python3.2/dist-packages/stem/interpreter/__init__.py", line 116, in main
      response = interpreter.run_command(user_input)
    File "/usr/local/lib/python3.2/dist-packages/stem/util/conf.py", line 276, in wrapped
      return func(*args, config = config, **kwargs)
    File "/usr/local/lib/python3.2/dist-packages/stem/interpreter/commands.py", line 317, in run_command
      output = self.do_info(arg)
    File "/usr/local/lib/python3.2/dist-packages/stem/interpreter/commands.py", line 184, in do_info
      for desc in server_desc_query:
    File "/usr/local/lib/python3.2/dist-packages/stem/descriptor/remote.py", line 328, in __iter__
      for desc in self._run(True):
    File "/usr/local/lib/python3.2/dist-packages/stem/descriptor/remote.py", line 317, in _run
      for desc in results:
    File "/usr/local/lib/python3.2/dist-packages/stem/descriptor/__init__.py", line 211, in parse_file
      for desc in file_parser(descriptor_file):
    File "/usr/local/lib/python3.2/dist-packages/stem/descriptor/__init__.py", line 261, in _parse_metrics_file
      for desc in stem.descriptor.server_descriptor._parse_file(descriptor_file, is_bridge = False, validate = validate, **kwargs):
    File "/usr/local/lib/python3.2/dist-packages/stem/descriptor/server_descriptor.py", line 146, in _parse_file
      if descriptor_content[0].startswith('@type'):
  TypeError: startswith first arg must be bytes or a tuple of bytes, not str

  https://trac.torproject.org/projects/tor/ticket/12185

There's a couple issues here. First is a last minute change I added to strip
@type annotations. It ran into the normal bytes/unicode python3 gotcha
resulting in the stacktrace above. The other is that our contact field is
bytes, so it needs to be converted to unicode before mingling with the other
lines.