Drop python 2.6 integ test serialization
When running our integ tests using python 2.6 we dropped test parallelization.
Turns out this no longer works, failing all asynchronous tests with...

  ======================================================================
  FAIL: test_cached_descriptor
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 152, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 227, in result
      test.fail(self._result.msg)
  AssertionError: Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 169, in _wrapper
      runner(*args) if args else runner()
  TypeError: test_cached_descriptor() takes exactly 1 argument (0 given)

Python 2.x is getting deprecated at the end of this year so rather than puzzle
over this lets simply drop the pretense at a python 2.6 hack. If we really need
python 2.6 testing I'll dig into what's up.