Allow stem.util.system integ testing without PATH
Checking that we have a PATH for the tests that require it...

  ======================================================================
  ERROR: test_pids_by_user
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/util/system.py", line 323, in test_pids_by_user
      self.assertTrue(os.getpid() in pids)
  TypeError: argument of type 'NoneType' is not iterable

  ======================================================================
  FAIL: test_is_available
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/util/system.py", line 82, in test_is_available
      self.assertTrue(stem.util.system.is_available('ls'))
  AssertionError: False is not true

  ======================================================================
  FAIL: test_pid_by_name
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/util/system.py", line 111, in test_pid_by_name
      self.assertEqual(tor_pid, stem.util.system.pid_by_name(tor_cmd))
  AssertionError: 2908 != None