Better validation of controller's from_port() function
I scratched my head due to an awefully misleading stacktrace when I passed a
port value into the method's argument slot. Validating the inputs to avoid
having this cause confusion in the future.

Before:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test/prompt.py", line 67, in controller
    controller = stem.control.Controller.from_port(CONTROL_PORT)
  File "stem/control.py", line 457, in from_port
    control_port = stem.socket.ControlPort(control_addr, control_port)
  File "stem/socket.py", line 287, in __init__
    if connect: self.connect()
  File "stem/socket.py", line 171, in connect
    self._socket = self._make_socket()
  File "stem/socket.py", line 311, in _make_socket
    control_socket.connect((self._control_addr, str(self._control_port)))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: coercing to Unicode: need string or buffer, int found

After:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test/prompt.py", line 67, in controller
    controller = stem.control.Controller.from_port(CONTROL_PORT)
  File "stem/control.py", line 459, in from_port
    raise ValueError("Invalid ip address: %s" % control_addr)
ValueError: Invalid ip address: 2779