Use getattr()/setattr() for mocking.mock_method
mocking.revert_mocking also needs setattr because it may be trying to
revert to the original method in an object.  This fixes the following
error when trying to use mock_method:

    TypeError: 'dictproxy' object does not support item assignment


Signed-off-by: Sean Robinson <seankrobinson@gmail.com>