Better exception when calling set_conf() with the wrong type
When calling set_conf() with other types, say an integer value, we failed
internally with...

  ======================================================================
  ERROR: test_transition_to_relay
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1411, in test_transition_to_relay
      controller.set_conf('OrPort', test.runner.ORPORT)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2332, in set_conf
      self.set_options({param: value}, False)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2395, in set_options
      query_comp.extend(['%s="%s"' % (param, val.strip()) for val in value])
  TypeError: 'int' object is not iterable

This is porbably a reasonably common mistake so providing a better response...

  ======================================================================
  ERROR: test_transition_to_relay
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1411, in test_transition_to_relay
      controller.set_conf('OrPort', test.runner.ORPORT)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2332, in set_conf
      self.set_options({param: value}, False)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2399, in set_options
      raise ValueError("Cannot set %s to %s since the value was a %s but we only accept strings" % (param, value, type(value).__name__))
  ValueError: Cannot set OrPort to 1113 since the value was a int but we only accept strings