Fix python3 unit test error
Oops, python3 regression slipped in with prior work...

  ======================================================================
  ERROR: test_connections
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python3.2/dist-packages/mock/mock.py", line 1305, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/util/proc.py", line 215, in test_connections
      tcp = b'%s\n 0: 11111111:1111 22222222:2222 01 44444444:44444444 55:55555555 66666666 1111        8 99999999' % TITLE_LINE
  TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'