Fix test_extendcircuit by removing int() conversion
Traceback:
  File "./test/integ/control/controller.py", line 464, in test_extendcircuit
    self.assertTrue(filter(lambda x: int(x.split()[0]) == circ_id, controller.get_info('circuit-status').splitlines()))
AssertionError: [] is not true

Also, change to standard variable name "circuit_id".