Immutability check for set_conf() didn't work with python3
Yet another bytes-verses-unicode gotcha.

  ======================================================================
  ERROR: test_set_conf_when_immutable
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 778, in test_set_conf_when_immutable
      self.assertRaisesRegexp(stem.InvalidArguments, "DisableAllSwap cannot be changed while tor's running", controller.set_conf, 'DisableAllSwap', '1')
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 272, in assertRaisesRegexp
      return super(original_type, self).assertRaisesRegexp(exc_type, exc_msg, func, *args, **kwargs)
    File "/usr/lib/python3.5/unittest/case.py", line 1311, in deprecated_func
      return original_func(*args, **kwargs)
    File "/usr/lib/python3.5/unittest/case.py", line 1258, in assertRaisesRegex
      return context.handle('assertRaisesRegex', args, kwargs)
    File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
      callable_obj(*args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2303, in set_conf
      self.set_options({param: value}, False)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2412, in set_options
      raise stem.InvalidRequest(response.code, response.message)
  stem.InvalidRequest: Transition not allowed: While Tor is running, changing DisableAllSwap is not allowed.

  ----------------------------------------------------------------------