Stacktrace when queue module is present
When running with the python 2.x if you have the queue module we use
io.StringIO rather than StringIO.StringIO. This causes two of our Controller's
methods to fail with...

  Traceback (most recent call last):
    File "circuits.py", line 7, in <module>
      for circ in sorted(controller.get_circuits()):
    File "/usr/lib/python2.7/site-packages/stem/control.py", line 455, in wrapped
      return func(self, *args, **kwargs)
    File "/usr/lib/python2.7/site-packages/stem/control.py", line 3284, in get_circuits
      circ_message = stem.socket.recv_message(StringIO('650 CIRC ' + circ + '\r\n'))
  TypeError: initial_value must be unicode or None, not str

Thanks to mancha for catching this!