Python 3 can't do comparison with other types
Another change in python 2 => 3 is that comparison ('<' and '>') can no longer
work with None, ints, and other types...

In python 2:

>>> 5 > None
True

In python 3:

>>> 5 > None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: int() > NoneType()

I expected the 'unorderable types' error would cause it to use the Version's
comparison function but evidently that's not the case. Rather, when using
python 3 callers need to check the values' type first (there's nothing we can
do to make the comparison work). Personally I think that this is pretty stupid,
but that's the workaround done by python devs on...

http://bugs.python.org/issue13545

Oh well. Dropping the test that comparison with None and ints work.

======================================================================
ERROR: test_nonversion_comparison
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/version.py", line 125, in test_nonversion_comparison
    self.assertTrue(test_version > None)
TypeError: unorderable types: Version() > NoneType()

----------------------------------------------------------------------
Ran 9 tests in 0.043s