Revert "Minor simplification for cache fetches"
This change broke the ability for get_info() to accept unicode inputs (or bytes
under python3)...

  >>> controller.get_network_status(u'0881E47137764C907E729C9303C094BD270CC27F')
  Traceback (most recent call last):
    File "<console>", line 1, in <module>
    File "/home/ubuntu/stem/stem/control.py", line 482, in wrapped
      return func(self, *args, **kwargs)
    File "/home/ubuntu/stem/stem/control.py", line 1928, in get_network_status
      desc_content = self.get_info(query, get_bytes = True)
    File "/home/ubuntu/stem/stem/control.py", line 482, in wrapped
      return func(self, *args, **kwargs)
    File "/home/ubuntu/stem/stem/control.py", line 1165, in get_info
      cached_results = self._get_cache_map(map(str.lower, params), 'getinfo')
  TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

This reverts commit e134dc59de93de3aef2ae1ec6e9b7a2f194c8eff.