Fixing python 3 compatablity for tordnsel test
======================================================================
ERROR: test_parse_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/descriptor/tordnsel.py", line 55, in test_parse_file
    descriptors = list(_parse_file(io.BytesIO(TEST_DESC)))
TypeError: 'str' does not support the buffer interface

----------------------------------------------------------------------
Ran 1 test in 0.001s