Check for signing support in cryptography module
Python 3.5.2 seems to have cryptography 1.2.3. This is highly out of date and
causes unit tests to fail with...

  ======================================================================
  ERROR: test_descriptor_signing
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/extrainfo_descriptor.py", line 139, in test_descriptor_signing
      RelayExtraInfoDescriptor.create(sign = True)
    File "/home/atagar/Desktop/stem/stem/descriptor/extrainfo_descriptor.py", line 986, in create
      return cls(cls.content(attr, exclude, sign, signing_key), validate = validate)
    File "/home/atagar/Desktop/stem/stem/descriptor/extrainfo_descriptor.py", line 978, in content
      return _append_router_signature(content, signing_key.private)
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 1040, in _append_router_signature
      signature = base64.b64encode(private_key.sign(content, padding.PKCS1v15(), hashes.SHA1()))
  AttributeError: '_RSAPrivateKey' object has no attribute 'sign'

  ----------------------------------------------------------------------

Current version of cryptography is 2.0.3, and the sign method was added in
1.4...

  https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#cryptography.hazmat.primitives.asymmetric.rsa.RSAPrivateKey.sign