Skipping repurpose_circuit() test if offline
The repurpose_circuit() test uses 'GETINFO circuit-status' results which are
empty when offline, causing an error...

======================================================================
ERROR: test_repurpose_circuit
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 386, in test_repurpose_circuit
    first_circ = controller.get_info('circuit-status').splitlines()[0].split()
IndexError: list index out of range

----------------------------------------------------------------------
Ran 14 tests in 1.390s