Fix test_close_stream assertion
When running our online target we might have multiple streams in process.
Fixing our assertion so we check if the stream we expect is present rather
than the only one.

  https://trac.torproject.org/projects/tor/ticket/30696

  ======================================================================
  FAIL: test_close_stream
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 57, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 57, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1072, in test_close_stream
      self.assertEqual([built_stream.id], [stream.id for stream in controller.get_streams()])
  AssertionError: Lists differ: ['48'] != ['48', '58', '473']

  Second list contains 2 additional elements.
  First extra element 1:
  '58'

  - ['48']
  + ['48', '58', '473']