All client usage failed with ValueErrors
When our Relay class sends a message it first drains its socket of unread
data...

  async def _msg(self, cell):
    await self._orport.recv(timeout = 0)
    await self._orport.send(cell.pack(self.link_protocol))
    response = await self._orport.recv(timeout = 1)
    yield stem.client.cell.Cell.pop(response, self.link_protocol)[0]

This in turn called asyncio.wait_for() with a timeout value of zero which
returns immediately, leaving our socket undrained.

Our following recv() is then polluted with unexpected data. For instance,
this is caused anything that uses create_circuit() (such as descriptor
downloads) to fail with confusing exceptions such as...

  ======================================================================
  ERROR: test_downloading_via_orport
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 60, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 75, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 75, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/descriptor/remote.py", line 27, in test_downloading_via_orport
      fall_back_to_authority = False,
    File "/home/atagar/Desktop/stem/stem/util/__init__.py", line 363, in _run_async_method
      return future.result()
    File "/home/atagar/Python-3.7.0/Lib/concurrent/futures/_base.py", line 432, in result
      return self.__get_result()
    File "/home/atagar/Python-3.7.0/Lib/concurrent/futures/_base.py", line 384, in __get_result
      raise self._exception
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 469, in run
      return [desc async for desc in self._run(suppress)]
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 469, in <listcomp>
      return [desc async for desc in self._run(suppress)]
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 482, in _run
      raise self.error
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 549, in _download_descriptors
      response = await asyncio.wait_for(self._download_from(endpoint), time_remaining)
    File "/home/atagar/Python-3.7.0/Lib/asyncio/tasks.py", line 384, in wait_for
      return await fut
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 588, in _download_from
      async with await relay.create_circuit() as circ:
    File "/home/atagar/Desktop/stem/stem/client/__init__.py", line 270, in create_circuit
      async for cell in self._msg(create_fast_cell):
    File "/home/atagar/Desktop/stem/stem/client/__init__.py", line 226, in _msg
      yield stem.client.cell.Cell.pop(response, self.link_protocol)[0]
    File "/home/atagar/Desktop/stem/stem/client/cell.py", line 182, in pop
      cls = Cell.by_value(command)
    File "/home/atagar/Desktop/stem/stem/client/cell.py", line 139, in by_value
      raise ValueError("'%s' isn't a valid cell value" % value)
  ValueError: '65' isn't a valid cell value

This also reverts our Relay's '_orport_lock' back to a threaded RLock because
asyncio locks are not reentrant, causing methods such as directory() (which
call _send()) to deadlock upon themselves. We might drop this lock entirely in
the future (thread safety should be moot now that the stem.client module is
fully asynchronous).