Long digest values caused stem.client errors
Interesting. Tests were happy on my laptop but on my PC where I have an older
python 2.7 and 3.x version there are errors...

  ======================================================================
  ERROR: test_relay_cell
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/client/cell.py", line 160, in test_relay_cell
      self.assertEqual(3257622417, RelayCell(5, 'RELAY_BEGIN_DIR', '', 3257622417, 564346860).digest)
    File "/home/atagar/Desktop/stem/stem/client/cell.py", line 315, in __init__
      raise ValueError('RELAY cell digest must be a hash, string, or int but was a %s' % type(digest).__name__)
  ValueError: RELAY cell digest must be a hash, string, or int but was a long

  ----------------------------------------------------------------------

Fixing our isinstance checks so they recognize both ints and longs. Two quick
things to note about this...

  * In python 2.7 this is usually done as "isinstance(my_value, (int, long))"
    but python3 drops the long type so that's a no-go.

  * When we drop the python 2.x series these should become
    "isinstance(my_value, int)" checks.