Mocking's sign_descriptor_content() incompatible with python 3.x
I didn't have a python 3.x copy of pycrypto installed, so there were some code
paths I didn't previously encounter. Unit tests failed due to
sign_descriptor_content() not explicitly using bytes at several points.

======================================================================
ERROR: test_mirror_mirror_on_the_wall_4
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/tutorial.py", line 169, in test_mirror_mirror_on_the_wall_4
    exit_descriptor = mocking.sign_descriptor_content(exit_descriptor)
  File "/home/atagar/Desktop/stem/test/data/python3/test/mocking.py", line 984, in sign_descriptor_content
    public_key_string = public_key_string[:64] + "\n" + public_key_string[64:128] + "\n" + public_key_string[128:]
TypeError: can't concat bytes to str

----------------------------------------------------------------------