Don't require additional arguments to make descriptor
These additional requirements broke an existing test. Not quite sure what
we'll do for this long term, but for the moment simply reverting to our
prior behavior so the test passes...

	======================================================================
	ERROR: test_invalid_lifetime
	----------------------------------------------------------------------
	Traceback (most recent call last):
  	File "/home/atagar/Desktop/stem/test/unit/descriptor/hidden_service_v3.py", line 191, in test_invalid_lifetime
    	expect_invalid_attr(self, {'descriptor-lifetime': test_value}, 'lifetime')
  	File "/home/atagar/Desktop/stem/test/unit/descriptor/__init__.py", line 41, in base_expect_invalid_attr
    	return base_expect_invalid_attr_for_text(cls, default_attr, default_value, test, cls.content(desc_attrs), attr, expected_value)
  	File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 978, in content
  	  raise ValueError('Need to provide a private ed25519 identity key to create a descriptor')
	ValueError: Need to provide a private ed25519 identity key to create a descriptor