Permit float in label functions
Oops. Actually, our last release allowed floats (and our 'decimal' argument
doesn't make terribly much sense otherwise). We *did* have a bug in that
remainder values that are less than 1 crashed us (corrected by commit c90e87c),
but we shouldn't have addressed that by integer normalization.

Regression caught thanks to Nyx's tests...

  ======================================================================
  FAIL: test_draw_line (panel.connection.TestConnectionPanel)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/nyx/test/__init__.py", line 59, in wrapped
      return func(self, *args, **kwargs)
    File "/usr/lib/python3.8/unittest/mock.py", line 1325, in patched
      return func(*newargs, **newkeywargs)
    File "/home/atagar/Desktop/nyx/test/panel/connection.py", line 228, in test_draw_line
      self.assertEqual(expected, rendered.content)
  AssertionError: ' 75.119.206.243:22 (de)      -->  82.121.9.9:3531              15.4s (INBOUND)' != ' 75.119.206.243:22 (de)      -->  82.121.9.9:3531              14.9s (INBOUND)'
  -  75.119.206.243:22 (de)      -->  82.121.9.9:3531              15.4s (INBOUND)
  ?                                                                 ^ ^
  +  75.119.206.243:22 (de)      -->  82.121.9.9:3531              14.9s (INBOUND)
  ?                                                                 ^ ^