Using byte string for binascii.a2b_hex in python 3
Like base64.b64decode(), binascii.a2b_hex() expects a byte string.

======================================================================
ERROR: test_valid_response
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/response/authchallenge.py", line 31, in test_valid_response
    stem.response.convert("AUTHCHALLENGE", control_message)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/response/__init__.py", line 117, in convert
    message._parse_message(**kwargs)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/response/authchallenge.py", line 40, in _parse_message
    self.server_hash = binascii.a2b_hex(value)
TypeError: 'str' does not support the buffer interface

----------------------------------------------------------------------
Ran 2 tests in 0.009s