Python3 regression in socket's recv_message()
Oops, shame on me for not testing with python3. Recent log truncation change
introduced a regression...

  ======================================================================
  ERROR: test_hs_desc_content_event
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/response/events.py", line 877, in test_hs_desc_content_event
      event = _get_event(HS_DESC_CONTENT_EVENT)
    File "/home/atagar/Desktop/stem/test/unit/response/events.py", line 458, in _get_event
      controller_event = mocking.get_message(content)
    File "/home/atagar/Desktop/stem/test/mocking.py", line 259, in get_message
      return stem.response.ControlMessage.from_str(content)
    File "/home/atagar/Desktop/stem/stem/response/__init__.py", line 160, in from_str
      msg = stem.socket.recv_message(StringIO(content))
    File "/home/atagar/Desktop/stem/stem/socket.py", line 601, in recv_message
      print([b'... %i more lines...' % (len(log_message_lines) - TRUNCATE_LOGS)])
  TypeError: unsupported operand type(s) for %: 'bytes' and 'int'

  ----------------------------------------------------------------------

Thanks to toralf for pointing this out. Trouble is that under python3 bytes
doesn't support % formatting at all...

  >>> b'hi %i' % 5
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  TypeError: unsupported operand type(s) for %: 'bytes' and 'int'

This is pretty pesky, and something they plan to change...

  http://legacy.python.org/dev/peps/pep-0461/