Error when reading CollecTor file twice
When a CollecTor file is already within our cache we validate its hash against
CollecTor's index. However, files we wrote to disk are decompressed by default
so the hash naturally mismatches.

  https://github.com/torproject/stem/issues/76

Reproduced this issue with the following script...

  import stem.descriptor.collector

  collector = stem.descriptor.collector.get_instance()
  desc_file = collector.files(descriptor_type = 'server-descriptor')[0]  # pick any arbitrary file

  print('Number of descriptors (first read): %s' % len(list(desc_file.read(directory = '/tmp/collector_cache'))))
  print('Number of descriptors (second read): %s' % len(list(desc_file.read(directory = '/tmp/collector_cache'))))

Before...

  % python demo.py
  Number of descriptors (first read): 3112
  Traceback (most recent call last):
    File "scrap.py", line 8, in <module>
      print('Number of descriptors (second read): %s' % len(list(desc_file.read(directory = '/tmp/collector_cache'))))
    File "/home/atagar/Desktop/stem/stem/descriptor/collector.py", line 273, in read
      path = self.download(directory, True, timeout, retries)
    File "/home/atagar/Desktop/stem/stem/descriptor/collector.py", line 335, in download
      raise OSError("%s already exists but mismatches CollecTor's checksum (expected: %s, actual: %s)" % (path, expected_hash, actual_hash))
  OSError: /tmp/collector_cache/server-descriptors-2005-12.tar already exists but mismatches CollecTor's checksum (expected: bf700d8b6143e310219b2ce2810abd82f94bc295c7f08e9f1a88989562e33b2f, actual: 32a5ea8fd761e5967fbb8d399742f0da7cbb1c79c1539f2e58cad2e668462652)

After...

  % python demo.py
  Number of descriptors (first read): 3112
  Number of descriptors (second read): 3112

We can either solve this by dropping the hash check or caching compressed
archives. Initially I leaned toward the former to expedite cache reads, but on
reflection the later is conceptually simpler. Essentially, is this a network
cache or a read cache? A network cache is safer in that if CollecTor replaces a
file (but keeps the same filename) this will catch the change.