Fix fallback directory unit test
Oops, forgot to re-run our unit tests after syncing. The relay used in our unit
tests is no longer present.

	======================================================================
	ERROR: test_from_cache
	----------------------------------------------------------------------
	Traceback (most recent call last):
  	File "/home/atagar/Desktop/stem/test/unit/directory/fallback.py", line 95, in test_from_cache
  	  self.assertEqual('5.39.92.199', fallbacks['0BEA4A88D069753218EAAAD6D22EA87B9A1319D6'].address)
	KeyError: '0BEA4A88D069753218EAAAD6D22EA87B9A1319D6'