Tests requiring man command can't work on bsd
Several tests skipped on OSX need to also be skipped on BSD. There were also
some other newer tests that probably aren't running on OSX.

  ======================================================================
  ERROR: test_saving_manual_as_config
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/tmp/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/tmp/stem/test/unit/manual.py", line 205, in test_saving_manual_as_config
      manual = stem.manual.Manual.from_man(EXAMPLE_MAN_PATH)
    File "/tmp/stem/stem/manual.py", line 495, in from_man
      categories, config_options = _get_categories(man_output), OrderedDict()
    File "/tmp/stem/stem/manual.py", line 666, in _get_categories
      if lines[-1] == '':
  IndexError: list index out of range

  ----------------------------------------------------------------------