Blank inputs cause server descriptor parsing to fail
Honestly I'm not digging in too much, but DocTor has started providing
me with notifications of...

  Unable to retrieve the present server descriptors...

  source: http://204.13.164.118:80/tor/server/all
  time: 12/20/2018 11:44
  error: Content conform to being a server descriptor:

We strip annotation whitespace if we have descritor content to parse but didn't
if we didnn't. No reason I can think of to not do so in both cases.