Unit tests failed if bz2 unavailable
Python has bz2 built in but when python's compiled it omits bz2 by default.
This causes our tests to fail with...

  ======================================================================
  FAIL: test_archived_bz2
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/reader.py", line 404, in test_archived_bz2
      self.assertEqual(expected_results, read_descriptors)
  AssertionError: Lists differ: ['router Amunet1 199.48.147.35 443 0 80\np[7520 chars]-\n'] != []

  First list contains 3 additional elements.
  First extra element 0:
  'router Amunet1 199.48.147.35 443 0 80\nplatform Tor 0.2.2.34 (git-f0e1ee98af443107) on Linux x86_64...

  Diff is 9261 characters long. Set self.maxDiff to None to see it.

  ----------------------------------------------------------------------
  Ran 27 tests in 0.115s