Fix issue causing tests to be unable to run
Oops, python 2.6 fixes added a regression breaking everything *except* python
2.6. Oops. :P

  Traceback (most recent call last):
    File "./run_tests.py", line 20, in <module>
      RUN_ASYNC_TESTS = true
  NameError: name 'true' is not defined