Check for openssl ed25519 support
Unit tests fail with several errors, the most common of which for me is a lack
of ed25519 support in openssl...

  ======================================================================
  ERROR: test_inner_layer
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/hidden_service_v3.py", line 119, in test_inner_layer
      self.assertEqual(4, len(desc.introduction_points))
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 1149, in __getattr__
      parsing_function(self, self._entries)
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 447, in _parse_v3_introduction_points
      enc_key = X25519PublicKey.from_public_bytes(base64.b64decode(enc_key_b64))
    File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/primitives/asymmetric/x25519.py", line 22, in from_public_bytes
      _Reasons.UNSUPPORTED_EXCHANGE_ALGORITHM
  cryptography.exceptions.UnsupportedAlgorithm: X25519 is not supported by this version of OpenSSL.

This is gonna require more work, but for the moment disabling these portions
when unavailable to cut down on test failures.