Missing runner import for stem.connection
One thing I dislike about python imports is that they can sometimes happen
transtively. If modoule A imports module B which imports module C then module A
seems to have a reference to module C. This gets confusing as hell because when
you see that the 'import B' is unused and remove it you get completely
unrelated errors.

Anywho, I got a slew of stacktraces while running the integ tests about a
missing import for stem.connection in the runner module...

======================================================================
ERROR: test_get_pid_by_port_netstat
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/integ/util/system.py", line 250, in test_get_pid_by_port_netstat
    elif not runner.is_ptraceable():
  File "/home/atagar/Desktop/stem/test/runner.py", line 415, in is_ptraceable
    tor_version = self.get_tor_version()
  File "/home/atagar/Desktop/stem/test/runner.py", line 569, in get_tor_version
    control_socket = self.get_tor_socket()
  File "/home/atagar/Desktop/stem/test/runner.py", line 536, in get_tor_socket
    stem.connection.authenticate(control_socket, CONTROL_PASSWORD, self.get_chroot())
AttributeError: 'module' object has no attribute 'connection'

I'm not really sure when this was introduced, but fixing it.