Our ONLINE target could fail with an undefined 'streams'
Doesn't make the test pass, but was masking the actual issue which is
"SocksError: [6] TTL expired".

======================================================================
ERROR: test_attachstream
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1206, in test_attachstream
    our_stream = [stream for stream in streams if stream.target_address == host][0]
UnboundLocalError: local variable 'streams' referenced before assignment