Fixing open() mock for python 3
Our unit tests were broken under python 3 due to needing a slightly different
mock for the open() function.

======================================================================
ERROR: test_mirror_mirror_on_the_wall_2
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/tutorial.py", line 107, in test_mirror_mirror_on_the_wall_2
    tutorial_example()
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/tutorial.py", line 95, in tutorial_example
    for desc in parse_file(open("/home/atagar/.tor/cached-consensus")):
FileNotFoundError: [Errno 2] No such file or directory: '/home/atagar/.tor/cached-consensus'