Accept bytes in is_valid_ipv4_address
With python3 byte arguments failed with...

  ======================================================================
  ERROR: test_is_valid_ipv4_address
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/util/connection.py", line 464, in test_is_valid_ipv4_address
      self.assertTrue(stem.util.connection.is_valid_ipv4_address(address))
    File "/home/atagar/Desktop/stem/stem/util/connection.py", line 415, in is_valid_ipv4_address
      if address.count('.') != 3:
  TypeError: a bytes-like object is required, not 'str'