Test runner tried to use non-existant print_error() function
In commit e751397 we removed the test.output.print_error() function in favor of
something less verbose. Somehow we missed its usage in test.runner - weird that
pyflakes didn't catch this...

Traceback (most recent call last):
  File "./run_tests.py", line 405, in <module>
    main()
  File "./run_tests.py", line 212, in main
    integ_runner.start(target, args.attribute_targets, args.tor_path, extra_torrc_opts = test.util.get_torrc_entries(target))
  File "/home/atagar/Desktop/stem/test/runner.py", line 310, in start
    self._start_tor(tor_cmd)
  File "/home/atagar/Desktop/stem/test/runner.py", line 718, in _start_tor
    test.output.print_error("  failed to start tor: %s\n" % exc)
AttributeError: 'module' object has no attribute 'print_error'

Also, the runner had a couple calls of...

test.runner.get_runner()

Those should obviously just be 'get_runner()', and only worked because of our
test.output import (damn python's transitive imports are stupidly confusing).