Exclude gedit backup files
Dropping files ending with a tilda. Found this through the following integ test
failure...

  ======================================================================
  FAIL: test_sdist_matches_git
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/runner.py", line 178, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/installation.py", line 104, in test_sdist_matches_git
      self.fail(INSTALL_MISMATCH_MSG + '\n'.join(issues))
  AssertionError: Running 'python setup.py sdist' doesn't match our git contents in the following way. The manifest in our setup.py may need to be updated...

    * test/unit/version.py~ isn't expected in our release tarball