DictWriter.writeheader() introduced in python 2.7
The writeheader() method of the DictWriter class was added in python 2.7,
breaking our 2.5 and 2.6 compatability...

======================================================================
ERROR: test_multiple_descriptor_types
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/unit/descriptor/export.py", line 91, in test_multiple_descriptor_types
    self.assertRaises(ValueError, export_csv,)
  File "/usr/lib/python2.6/unittest.py", line 336, in failUnlessRaises
    callableObj(*args, **kwargs)
  File "/home/atagar/Desktop/stem/stem/descriptor/export.py", line 39, in export_csv
    export_csv_file(output_buffer, descriptors, included_fields, excluded_fields, header)
  File "/home/atagar/Desktop/stem/stem/descriptor/export.py", line 91, in export_csv_file
    writer.writeheader()
AttributeError: DictWriter instance has no attribute 'writeheader'

Noting the prereq in our pydocs and ignoring the 'header' flag if we can't
support it.