Fix difference in setuptools installation paths
An assertion that we install all our expected files is failing...

  ======================================================================
  FAIL: test_install
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 141, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 208, in result
      test.fail(self._result.msg)
  AssertionError: The following files were expected to be in our installation but weren't. Maybe our setup.py needs to be updated?

  stem/directory.py
  stem/util/ed25519.py
  stem/descriptor/networkstatus.py
  ...

The trouble is that setuptools adds an extra directory...

  distutil path:   [install-prefix]/lib/python3.7/site-packages/stem/version.py
  setuptools path: [install-prefix]/lib/python3.7/site-packages/stem-1.8.0.dev0-py3.7.egg/stem/version.py

Adjusting our glob to account for this difference.