Python 2.6 broken by OrderedDict usage
In our recent release I swapped our stem.util.conf to use an OrderedDict,
breaking our support for python 2.6...

  % python2.6 ./run_tests.py --unit
  Traceback (most recent call last):
    File "./run_tests.py", line 465, in <module>
      main()
    File "./run_tests.py", line 119, in main
      test_config.load(os.path.join(STEM_BASE, "test", "settings.cfg"))
    File "/home/atagar/Desktop/stem/stem/util/conf.py", line 504, in load
      self.set(key, value, False)
    File "/home/atagar/Desktop/stem/stem/util/conf.py", line 604, in set
      listener(self, key)
    File "/home/atagar/Desktop/stem/stem/util/conf.py", line 175, in update
      new_value = config.get(key, self.config_dict[key])
    File "/home/atagar/Desktop/stem/stem/util/conf.py", line 685, in get
      valMap = collections.OrderedDict()
  AttributeError: 'module' object has no attribute 'OrderedDict'

Caught by pmezard on...

  https://trac.torproject.org/12223

This is actually something we've already dealt with elsewhere. Stem contains
its own python 2.6 compatable copy of the OrderedDict module, I just forgot to
use it here.