Providing a string when str() is called on descriptors
Python 2.x gets pretty confused when an object's __str__ method provides a
unicode string. Calling...

>>> str(desc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 28: ordinal not in range(128)

Providing an ascii str in python 2.x and unicode str in python 3.x. Thanks to
Sathyanarayanan for the catch!