Fixing server descriptor test expecting unicode
One of the server descriptor integ tests had a failing assertion because the
expected text was ASCII bytes and the descriptor content was unicode. Fixing
the test and moving the to_unicode helper to str_tools where it belongs.

======================================================================
FAIL: test_non_ascii_descriptor
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/descriptor/server_descriptor.py", line 221, in test_non_ascii_descriptor
    self.assertEquals(expected_contact, desc.contact)
AssertionError: '2048R/F171EC1F Johan BlÃ¥bÃ¤ck ã\x81\x93ã\x82\x93ã\x81«ã\x81¡ã\x81¯' != '2048R/F171EC1F Johan Blåbäck こんにちは'
- 2048R/F171EC1F Johan BlÃ¥bÃ¤ck ããã«ã¡ã¯
+ 2048R/F171EC1F Johan Blåbäck こんにちは