Fix and re-sync fallback directory information
Oops, seems I haven't run this since reshuffling things into a stem.directory
module...

  % ./cache_fallback_directories.py
  Latest tor commit editing fallback directories: 63b4ea22af8e8314dd718f02046de5f4b91edf9d
  Current stem commit: 206b50519dbdf2881cf72cf9f0cbae453db08ede

  Traceback (most recent call last):
    File "./cache_fallback_directories.py", line 42, in <module>
      cached_fallback_directories = stem.directory.FallbackDirectory.from_cache()
  AttributeError: 'module' object has no attribute 'FallbackDirectory'