Validate address before connecting
Oops, the Address constructor indeed validates addresses *but* it was called
after we established a socket. As such our integ tests failed with...

  ======================================================================
  ERROR: test_invalid_arguments
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/integ/client/connection.py", line 20, in test_invalid_arguments
      self.assertRaisesRegexp(ValueError, "'nope' isn't an IPv4 or IPv6 address", Relay.connect, 'nope', 80)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 278, in assertRaisesRegexp
      return super(original_type, self).assertRaisesRegexp(exc_type, exc_msg, func, *args, **kwargs)
    File "/usr/lib/python2.7/unittest/case.py", line 993, in assertRaisesRegexp
      callable_obj(*args, **kwargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/client/__init__.py", line 80, in connect
      conn = stem.socket.RelaySocket(address, port)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/socket.py", line 378, in __init__
      self.connect()
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/socket.py", line 177, in connect
      self._socket = self._make_socket()
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/socket.py", line 418, in _make_socket
      raise stem.SocketError(exc)
  SocketError: [Errno -2] Name or service not known

  ----------------------------------------------------------------------