Avoiding stem imports in setup.py
Our setup.py may be ran under python 2.x or 3.x. Because of this the file and
anything it imports needs to run under both python serieses *without* a 2to3
conversion.

We were importing basic module information from __init__ which in turn brought
in the enum and str_tools utils...

atagar@morrigan:~/Desktop/stem$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from stem import __version__, \
  File "/home/atagar/Desktop/stem/stem/__init__.py", line 504, in <module>
    "ERR",
  File "/home/atagar/Desktop/stem/stem/util/enum.py", line 64, in UppercaseEnum
    return Enum(*[(v, v) for v in args])
  File "/home/atagar/Desktop/stem/stem/util/enum.py", line 77, in __init__
    if isinstance(entry, (bytes, unicode)):
NameError: global name 'unicode' is not defined

Bug caught by Dererk.