Expand installation test failure message
We recently adjusted our setup.py and though it passes locally, Jenkins is
sad...

  ======================================================================
  FAIL: test_install
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 141, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 208, in result
      test.fail(self._result.msg)
  AssertionError: Unable to install with 'python setup.py install': /usr/bin/python3 setup.py install --prefix /tmp/stem_test returned exit status 1

Adding our stdout and stderr to the exception output so we get more to go on.