Making SocksiPy work with official version
Ashish's SocksiPy was based on a fork of the main project...

https://code.google.com/p/socksipy-branch/

This caused my attempts to run it to fail with...

Traceback (most recent call last):
  File "twitter_script", line 12, in <module>
    socks.wrapmodule(urllib)
AttributeError: 'module' object has no attribute 'wrapmodule'

Making this work with the official upstream project is trivial so making the
tweak.