Checking that to_bytes has unicode before converting
Adding a check to the to_bytes() helper so we don't attempt to convert ASCII
bytes to ASCII bytes (which doesn't work so well).

======================================================================
ERROR: test_old_descriptor
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/descriptor/server_descriptor.py", line 120, in test_old_descriptor
    desc = stem.descriptor.server_descriptor.RelayDescriptor(descriptor_contents)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/server_descriptor.py", line 642, in __init__
    self._validate_content()
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/server_descriptor.py", line 687, in _validate_content
    key_der_as_hash = hashlib.sha1(stem.util.str_tools.to_bytes(key_as_bytes)).hexdigest()
  File "/home/atagar/Desktop/stem/test/data/python3/stem/util/str_tools.py", line 73, in to_bytes
    return _to_bytes(msg)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/util/str_tools.py", line 54, in _to_bytes
    return codecs.latin_1_encode(msg)[0]
TypeError: Can't convert 'bytes' object to str implicitly