SHA3 requires python 3.6 or pysha3
Hashlib's sha3_256() method was only recently added in python 3.6...

  https://docs.python.org/3/library/hashlib.html

  ======================================================================
  ERROR: test_for_decrypt
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/hidden_service_v3.py", line 53, in test_for_decrypt
      desc._decrypt('sltib6sxkuxh2scmtuvd5w2g7pahnzkovefxpo4e4ptnkzl5kkq5h2ad.onion')
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 576, in _decrypt
      identity_public_key = stem.descriptor.hsv3_crypto.decode_address(onion_address)
    File "/home/atagar/Desktop/stem/stem/descriptor/hsv3_crypto.py", line 55, in decode_address
      my_checksum = hashlib.sha3_256(my_checksum_body).digest()
  AttributeError: 'module' object has no attribute 'sha3_256'

  ----------------------------------------------------------------------

If unavailable then falling back to pysha3, and if that's unavailable as well
we'll need to raise an ImportError.