Standardize hash handling
Any time we define an __eq__() method we need to define __hash__() as well,
otherwise using the class as a hash key fails under python 3.x with...

  TypeError: unhashable type: 'DirectoryAuthority'

Regression caught by dgoulet for the DirectoryAuthority class so taking this as
an opportunety to ensure all our classes are in sync with their equality and
hashing.