Tests required sqlite3
Python includes sqlite3 as a builtin, but when you compile python yourself it
isn't included by default. Our stem.manual attempted to account for this but
our tests didn't, and with python3 the module raises a ModuleNotFoundError
rather than an ImportError.

  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/task.py", line 160, in _import_tests
      importlib.import_module(module.rsplit('.', 1)[0])
    File "/home/atagar/Python-3.8.1/Lib/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/atagar/Desktop/stem/test/unit/manual.py", line 8, in <module>
      import sqlite3
    File "/home/atagar/Python-3.8.1/Lib/sqlite3/__init__.py", line 23, in <module>
      from sqlite3.dbapi2 import *
    File "/home/atagar/Python-3.8.1/Lib/sqlite3/dbapi2.py", line 27, in <module>
      from _sqlite3 import *
  ModuleNotFoundError: No module named '_sqlite3'