Fix certificate byte encoding
======================================================================
ERROR: test_encode_decode_certificate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/require.py", line 57, in wrapped
    return func(self, *args, **kwargs)
  File "/home/atagar/Desktop/stem/test/unit/descriptor/certificate.py", line 217, in test_encode_decode_certificate
    ed_cert_bytes = my_ed_cert.encode()
  File "/home/atagar/Desktop/stem/stem/descriptor/certificate.py", line 418, in encode
    obj += self.version.to_bytes(1, 'big')
AttributeError: 'int' object has no attribute 'to_bytes'