Include PYTHONPATH within install test
Damn I hate remote debugging. Our installation tests work for me, but fail
under Jenkins with the following. Experimentally adding a PYTHONPATH to see if
that does the trick.

  ======================================================================
  FAIL: test_install
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 141, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/util/test_tools.py", line 208, in result
      test.fail(self._result.msg)
  AssertionError: Unable to install with 'python setup.py install': /usr/bin/python3 setup.py install --prefix /tmp/stem_test returned exit status 1
  ----------------------------------------
  stdout:
  ----------------------------------------
  running install
  Checking .pth file support in /tmp/stem_test/lib/python3.7/site-packages/
  /usr/bin/python3 -E -c pass
  ----------------------------------------
  stderr:
  ----------------------------------------
  /usr/lib/python3/dist-packages/setuptools/dist.py:475: UserWarning: Normalizing '1.8.0-dev' to '1.8.0.dev0'
    normalized_version,
  TEST FAILED: /tmp/stem_test/lib/python3.7/site-packages/ does NOT support .pth files
  error: bad install directory or PYTHONPATH

  You are attempting to install a package to a directory that is not
  on PYTHONPATH and which Python does not read ".pth" files from.  The
  installation directory you specified (via --install-dir, --prefix, or
  the distutils default setting) was:

      /tmp/stem_test/lib/python3.7/site-packages/

  and your PYTHONPATH environment variable currently contains:

      ''

  Here are some of your options for correcting the problem:

  * You can choose a different installation directory, i.e., one that is
    on PYTHONPATH or supports .pth files

  * You can add the installation directory to the PYTHONPATH environment
    variable.  (It must then also be on PYTHONPATH whenever you run
    Python and want to use the package(s) you are installing.)

  * You can set up the installation directory to support ".pth" files by
    using one of the approaches described here:

    https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations

  Please make the appropriate changes for your system and try again.