Setuptools egg-info paths differ
Another test failure due to a minor difference between distutil and
setuptools...

  ======================================================================
  FAIL: test_install
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 141, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 208, in result
      test.fail(self._result.msg)
  AssertionError: The following files weren't expected to be in our installation.

  EGG-INFO/scripts/tor-prompt
  EGG-INFO/dependency_links.txt
  EGG-INFO/PKG-INFO
  EGG-INFO/not-zip-safe
  EGG-INFO/top_level.txt
  EGG-INFO/SOURCES.txt

Distutil has a single egg info file...

  [install-prefix]/lib/python3.7/site-packages/stem-1.8.0_dev-py3.7.egg-info

Whereas setuptools creates several.