Process renaming requires ASCII bytes
Yet another unicode/ASCII compatability issue...

======================================================================
ERROR: test_set_process_name
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/util/system.py", line 409, in test_set_process_name
    stem.util.system.set_process_name("stem_integ")
  File "/home/atagar/Desktop/stem/test/data/python3/stem/util/system.py", line 764, in set_process_name
    _set_prctl_name(process_name)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/util/system.py", line 809, in _set_prctl_name
    name_buffer.value = process_name
TypeError: str/bytes expected instead of str instance

During handling of the above exception, another exception occurred:

Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/util/system.py", line 412, in test_set_process_name
    stem.util.system.set_process_name(initial_name)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/util/system.py", line 764, in set_process_name
    _set_prctl_name(process_name)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/util/system.py", line 809, in _set_prctl_name
    name_buffer.value = process_name
TypeError: str/bytes expected instead of str instance