Ensure CLOCK_TICK is what we expect for unit tests
yurivict271 points out that several tests of ours are failing on FreeBSD. First
one is a unit test. The values are based on a CLOCK_TICK constant so that's
probably why our results differ.

  ======================================================================
  FAIL: test_stats
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
      return func(*args, **keywargs)
    File "/usr/ports/security/py-stem/work/stem-1.5.4/test/unit/util/proc.py", line 138, in test_stats
      self.assertEqual(response, proc.stats(24062, *args))
  AssertionError: Tuples differ: ('0.13',) != ('0.1015625',)

  First differing element 0:
  '0.13'
  '0.1015625'

  - ('0.13',)
  + ('0.1015625',)

  ----------------------------------------------------------------------
  Ran 10 tests in 0.021s