Mocking for open() broken in python 3
In python 2.x there's both __builtin__.open() and io.open(), but in python 3.x
there's just io.open() (which is aliased by builtin). Accounting for this when
we mock it for the descriptor reader unit tests.

I'm a little puzzled why the mocking wasn't failing more spectacularly before
(the __builtin__ import should always fail on python 3), but oh well - fixed
now.

With this the unit tests finally pass with python 3!!!

======================================================================
ERROR: test_load_processed_files
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/descriptor/reader.py", line 52, in test_load_processed_files
    self.assertEquals(expected_value, stem.descriptor.reader.load_processed_files(""))
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/reader.py", line 179, in load_processed_files
    with open(path) as input_file:
IOError: [Errno 2] No such file or directory: ''

======================================================================
FAIL: test_get_connections
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/unit/util/proc.py", line 171, in test_get_connections
    self.assertEquals(expected_results, proc.get_connections(pid))
AssertionError: Lists differ: [('17.17.17.17', 4369, '34.34.... != []

First list contains 2 additional elements.
First extra element 0:
('17.17.17.17', 4369, '34.34.34.34', 8738)

+ []
- [('17.17.17.17', 4369, '34.34.34.34', 8738),
- ]