Fix exception type for ephemeral hidden service fallback
Modern tor versions provide an empty response when no ephemereal hidden service
is present...

  >>> GETINFO onions/current
  250-onions/current=
  250 OK

  >>> GETINFO onions/detached
  250-onions/detached=
  250 OK

But at least as of our tor-0.2.9.14 branch we raise an exception instead. We
attempted to catch these exceptions, but evidently caught the wrong type. Iirc
I changed our GETINFO exception raising behavior a while back so maybe this
slipped in then.

Caught thanks to 0xrichard...

  https://trac.torproject.org/projects/tor/ticket/30422

  ======================================================================
  ERROR: test_ephemeral_hidden_services_v2
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 57, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 57, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 559, in test_ephemeral_hidden_services_v2
      self.assertEqual([], controller.list_ephemeral_hidden_services())
    File "/home/atagar/Desktop/stem/stem/control.py", line 480, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/control.py", line 2916, in list_ephemeral_hidden_services
      result += self.get_info('onions/current').split('\n')
    File "/home/atagar/Desktop/stem/stem/control.py", line 480, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/control.py", line 1200, in get_info
      stem.response.convert('GETINFO', response)
    File "/home/atagar/Desktop/stem/stem/response/__init__.py", line 123, in convert
      message._parse_message(**kwargs)
    File "/home/atagar/Desktop/stem/stem/response/getinfo.py", line 46, in _parse_message
      raise stem.OperationFailed(error_code, error_msg)
  OperationFailed: No onion services of the specified type.