Python3 unit test regressions with new Descriptor.from_str() tests
Oops, couple unicode-vs-bytes mistakes...

  https://trac.torproject.org/projects/tor/ticket/28550

  ======================================================================
  ERROR: test_from_str_multiple
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/descriptor.py", line 45, in test_from_str_multiple
      RelayDescriptor.content({'router': 'relay2 71.35.133.197 9001 0 0'}),
  TypeError: sequence item 1: expected str instance, bytes found

  ======================================================================
  ERROR: test_from_str_type_handling
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/descriptor.py", line 33, in test_from_str_type_handling
      desc = Descriptor.from_str('@type server-descriptor 1.0\n' + desc_text)
  TypeError: Can't convert 'bytes' object to str implicitly

  ----------------------------------------------------------------------

I'm also making from_str() normalize unicode to bytes so the method isn't a
misnomer for python3.