Stacktrace when running individual tests
When running individual tests we don't trigger static checks. This in turn
caused our recent multithreading optimization to throw a stacktrace...

  Traceback (most recent call last):
    File "./run_tests.py", line 457, in <module>
      main()
    File "./run_tests.py", line 331, in main
      task.join()
    File "/home/atagar/Desktop/stem/test/task.py", line 206, in join
      self.result = self._background_pipe.recv()
  AttributeError: 'NoneType' object has no attribute 'recv'