With python3 map can't be indexed into
With python 3.2 it's fine but our integ tests fail under 3.6 with...

  ======================================================================
  ERROR: test_install
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 43, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/installation.py", line 118, in test_install
      self.assertEqual(stem.__version__, stem.util.system.call([PYTHON_EXE, '-c', "import sys;sys.path.insert(0, '%s');import stem;print(stem.__version__)" % INSTALL_PATH])[0])
    File "/home/atagar/Desktop/stem/stem/util/system.py", line 1083, in call
      is_shell_command = command_list[0] in SHELL_COMMANDS
  TypeError: 'map' object is not subscriptable