Only validate RELAY cells when unencrypted
When the cell is encrypted these fields are obviously essentially noise. In
practice this seems to be causing inconsistent failures roughly 1/10 of the
time...

  Traceback (most recent call last):
    File "client-or-stream-raw.py", line 30, in <module>
      reply = circ.send('RELAY_BEGIN_DIR', stream_id = 1)
    File "/home/atagar/Desktop/tor/endosome/stem/client/__init__.py", line 246, in send
      reply = next(stem.client.cell.Cell.unpack(self.relay._orport.recv(), self.relay.link_protocol))
    File "/home/atagar/Desktop/tor/endosome/stem/client/cell.py", line 135, in unpack
      cell, content = Cell.pop(content, link_protocol)
    File "/home/atagar/Desktop/tor/endosome/stem/client/cell.py", line 166, in pop
      return cls._unpack(payload, circ_id, link_protocol), content
    File "/home/atagar/Desktop/tor/endosome/stem/client/cell.py", line 349, in _unpack
      return RelayCell(circ_id, command, data, digest, stream_id, recognized)
    File "/home/atagar/Desktop/tor/endosome/stem/client/cell.py", line 327, in __init__
      raise ValueError('%s relay cells concern the circuit itself and cannot have a stream id' % self.command)
  ValueError: RELAY_TRUNCATE relay cells concern the circuit itself and cannot have a stream id