Using binary mode for the controller socket file
Yay! Now that I have a version of python 3 that doesn't segfault I can finish
making our integ tests work.

The socket file used for controller connections should be normalized to use
binary mode. This is its behavior in python 2.x, and in 3.x having it in text
mode can cause sadness.

Exception in thread Tor Listener:
Traceback (most recent call last):
  File "/home/atagar/Desktop/Python-3.3.0/Lib/threading.py", line 639, in _bootstrap_inner
    self.run()
  File "/home/atagar/Desktop/Python-3.3.0/Lib/threading.py", line 596, in run
    self._target(*self._args, **self._kwargs)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/control.py", line 573, in _reader_loop
    control_message = self._socket.recv()
  File "/home/atagar/Desktop/stem/test/data/python3/stem/socket.py", line 115, in recv
    return recv_message(socket_file)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/socket.py", line 539, in recv_message
    line = control_file.readline()
  File "/home/atagar/Desktop/Python-3.3.0/Lib/codecs.py", line 300, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 2005: invalid continuation byte

After addressing this and a few encoding issues the controller integ tests now
pass, but after we're done testing python spews out a dump following...

*** glibc detected *** python3: munmap_chunk(): invalid pointer: 0x097f1620 ***

At this point I'm pretty well persuaded that the python 3.x series leaves
something to be desired in terms of stability.