Regression in RUN_PTRACE target
Oops, one of our testing changes caused RUN_PTRACE (and by extension RUN_ALL)
to start failing...

  Traceback (most recent call last):
    File "./run_tests.py", line 474, in <module>
      main()
    File "./run_tests.py", line 277, in main
      if target_prereq and our_version < stem.version.Requirement(target_prereq):
  TypeError: 'Enum' object is not callable