Stacktrace when CircuitEvent compared
Nyx is getting stacktraces which are due to referring to an attribute that
doesn't exist. CircuitEvents aren't documented as having a socks_port but they
*do* have a socks_password...

  File "/home/atagar/Desktop/nyx/nyx/panel/connection.py", line 625, in _update
    new_entries.append(Entry.from_circuit(circ))
  File "/home/atagar/Desktop/nyx/stem/util/lru_cache.py", line 122, in wrapper
    link = cache_get(key)
  File "/home/atagar/Desktop/nyx/stem/response/events.py", line 419, in __eq__
    return self._compare(other, lambda s, o: s == o)
  File "/home/atagar/Desktop/nyx/stem/response/events.py", line 392, in _compare
    my_attr = getattr(self, attr)
  AttributeError: 'CircuitEvent' object has no attribute 'socks_port'