Using stem.descriptor.parse_file() for extrainfo integ tests
Going through parse_file() so we do the proper unicode conversion.

======================================================================
ERROR: test_cached_descriptor
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/descriptor/extrainfo_descriptor.py", line 150, in test_cached_descriptor
    for desc in stem.descriptor.extrainfo_descriptor._parse_file(descriptor_file):
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/extrainfo_descriptor.py", line 155, in _parse_file
    extrainfo_content = stem.descriptor._read_until_keywords("router-signature", descriptor_file)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/descriptor/__init__.py", line 350, in _read_until_keywords
    line_match = KEYWORD_LINE.match(line)
TypeError: can't use a string pattern on a bytes-like object