Fixing AttributeError in use_directory_mirrors()
Correcting a couple issues, one in the tests and another in the remote
descriptor module, causing integ failures.

======================================================================
ERROR: test_use_directory_mirrors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/integ/descriptor/remote.py", line 62, in test_use_directory_mirrors
    downloader.use_directory_mirrors()
  File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 419, in use_directory_mirrors
    if Flag.V2DIR in desc.flags:
AttributeError: 'str' object has no attribute 'flags'

======================================================================
ERROR: test_using_authorities
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/integ/descriptor/remote.py", line 34, in test_using_authorities
    for authority, (address, dirport) in stem.descriptor.remote.DIRECTORY_AUTHORITIES.items():