Only require onion addresses when decrypting
Minor tweek so a few of our tests can pass...

  ======================================================================
  ERROR: test_invalid_lifetime
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/hidden_service_v3.py", line 110, in test_invalid_lifetime
      expect_invalid_attr(self, {'descriptor-lifetime': test_value}, 'lifetime')
    File "/home/atagar/Desktop/stem/test/unit/descriptor/__init__.py", line 41, in base_expect_invalid_attr
      return base_expect_invalid_attr_for_text(cls, default_attr, default_value, test, cls.content(desc_attrs), attr, expected_value)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/__init__.py", line 52, in base_expect_invalid_attr_for_text
      desc = cls(desc_text, validate = False)
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 540, in __init__
      raise ValueError("The onion address MUST be provided to parse a V3 descriptor")
  ValueError: The onion address MUST be provided to parse a V3 descriptor