Update cache contents
Trying to get our ONLINE target to pass so we can add a new integ test for
consensus signing. Tests check that the manual and fallback contents are up to
date so appeasing that.

Turns out fallback caching was still broken because orport_v6 is a tuple, not a
single value...

  Traceback (most recent call last):
    File "./cache_fallback_directories.py", line 51, in <module>
      print(stem.descriptor.remote._fallback_directory_differences(cached_fallback_directories, latest_fallback_directories))
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 1109, in _fallback_directory_differences
      '  orport_v6: %s' % (directory.orport_v6 if directory.orport_v6 else '[none]'),
  TypeError: not all arguments converted during string formatting

This target doesn't pass yet...

  ======================================================================
  FAIL: test_has_all_tor_config_options
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/manual.py", line 284, in test_has_all_tor_config_options
      self.fail("The %s config options in our man page aren't presently supported by tor. Are we using the latest git commit of tor? If so, maybe we need to remove them?" % ', '.join(extra_in_manual))
  AssertionError: The PredictedPortsRelevanceTime, CircuitIdleTimeout config options in our man page aren't presently supported by tor. Are we using the latest git commit of tor? If so, maybe we need to remove them?

... but think this last bit is a tweak we need to make in the tor manual...

  https://trac.torproject.org/projects/tor/ticket/22257