Async event handling for BaseController
Implementation for the BaseController. This continually pulls from the control
socket, providing three things...

- asynchronous events are sent to a callback
- msg() function which sends a message and provides back the response
- functional is_alive() check (we need a continuous puller to know when the
  socket is closed)

These are done in a similar fashion as the TorCtl class except that I'm aiming
to provide thread safety. That said, I haven't got it right yet. Controller
tests inconsistently fail with...

- deadlock
- seg faults (... not good, indicates a python bug)
- occasional nonsensical stack trace on shutdown:

  Exception in thread Tor Listener (most likely raised during interpreter shutdown):
  Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    File "/usr/lib/python2.7/threading.py", line 505, in run
    File "/home/atagar/Desktop/stem/stem/control.py", line 389, in _reader_loop
  <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'socket'

Needless to say, all of this needs to be fixed. However, I've been banging my
head against these concurrency issues for days so I should finally commit what
I have.