Test accidently left around a file in /tmp
The test_save_processed_files_malformed checks that save_processed_files()
fails when presented with malformed data. However, this function still writes
out a blank file. I noticed this because I just tried running the tests as a
different user from prior test runs, causing...

======================================================================
ERROR: test_save_processed_files_malformed
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/integ/descriptor/reader.py", line 172, in test_save_processed_files_malformed
    self.assertRaises(TypeError, stem.descriptor.reader.save_processed_files, "/tmp/foo", listing)
  File "/usr/lib/python2.7/unittest/case.py", line 465, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/atagar/Desktop/stem/stem/descriptor/reader.py", line 229, in save_processed_files
    with open(path, "w") as output_file:
IOError: [Errno 13] Permission denied: '/tmp/foo'

----------------------------------------------------------------------
Ran 21 tests in 1.558s