Converting str stats for proc tests
The proc tests were comparing strings with floats. It coincidentally passed,
but wasn't really testing what we wanted. In python 3.x the comparisons fail
due to the type mismatch.

======================================================================
ERROR: test_get_stats
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/util/proc.py", line 74, in test_get_stats
    self.assertTrue(utime > 0)
TypeError: unorderable types: str() > int()