Integ failure for HiddenServiceNonAnonymousMode with older tor versions
Tor's HiddenServiceNonAnonymousMode option is rather new. Nice that we have an
integ test for it, but we should account for versions without it too...

  ======================================================================
  FAIL: test_unanonymous_hidden_service_config_must_match
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 150, in <lambda>
      self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 212, in result
      test.fail(self._result.msg)
  AssertionError: Expected 'Process terminated: HiddenServiceNonAnonymousMode does not provide any server anonymity. It must be used with HiddenServiceSingleHopMode set to 1.' but was 'Process terminated: Unknown option 'HiddenServiceNonAnonymousMode'.  Failing.'