Fix python3 testing regression
The addition of assertRaisesWith is causing unit test failures with python3...

	======================================================================
	FAIL: test_pack
	----------------------------------------------------------------------
	ValueError: b'\x00\x12' is the wrong size for a BAD_SIZE field

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
  	File "/home/atagar/Desktop/stem/test/unit/client/size.py", line 29, in test_pack
    	self.assertRaisesWith(ValueError, "'\\x00\\x12' is the wrong size for a BAD_SIZE field", bad_size.pack, 18)
  	File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 280, in assertRaisesWith
   	  return self.assertRaisesRegexp(exc_type, '^%s$' % re.escape(exc_msg), func, *args, **kwargs)
  	File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 290, in assertRaisesRegexp
  	  return super(original_type, self).assertRaisesRegexp(exc_type, exc_msg, func, *args, **kwargs)
	AssertionError: "^\'\\x00\\x12\'\ is\ the\ wrong\ size\ for\ a\ BAD_SIZE\ field$" does not match "b'\x00\x12' is the wrong size for a BAD_SIZE field"

	----------------------------------------------------------------------

Trouble is that b'' prefix added to byte representations in python3. That's
fine, I don't mind if it's in the message or not so simply going back to our
prior assertion.