Stacktrace if stem.connection.connect gets a string port argument
Oops. When we present a string rather than int for a port argument we
stacktrace. Caught while looking into ways we can improve a script by
toralf.

  Traceback (most recent call last):
    File "info.py", line 191, in <module>
      main()
    File "info.py", line 57, in main
      with stem.connection.connect(control_port = ('127.0.0.1', control_port)) as controller:
    File "/home/atagar/Desktop/tor/tor-utils/stem/connection.py", line 277, in connect
      control_connection = stem.socket.ControlPort(address, port)
    File "/home/atagar/Desktop/tor/tor-utils/stem/socket.py", line 376, in __init__
      self.connect()
    File "/home/atagar/Desktop/tor/tor-utils/stem/socket.py", line 247, in connect
      self._socket = self._make_socket()
    File "/home/atagar/Desktop/tor/tor-utils/stem/socket.py", line 402, in _make_socket
      control_socket.connect((self._control_addr, self._control_port))
    File "/usr/lib/python2.7/socket.py", line 228, in meth
      return getattr(self._sock,name)(*args)
  TypeError: an integer is required