Hex method unavailable in python 2.x
Python 3.5 added the hex() method. Prior to that binascii is used for hex
conversion.

  https://stackoverflow.com/questions/6624453/whats-the-correct-way-to-convert-bytes-to-a-hex-string-in-python-3

  ======================================================================
  ERROR: test_for_decrypt
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/hidden_service_v3.py", line 57, in test_for_decrypt
      desc._decrypt('sltib6sxkuxh2scmtuvd5w2g7pahnzkovefxpo4e4ptnkzl5kkq5h2ad.onion')
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 581, in _decrypt
      subcredential_bytes = stem.descriptor.hsv3_crypto.get_subcredential(identity_public_key_bytes, blinded_key_bytes)
    File "/home/atagar/Desktop/stem/stem/descriptor/hsv3_crypto.py", line 112, in get_subcredential
      print('public_identity_key: %s' % (public_identity_key.hex()))
  AttributeError: 'str' object has no attribute 'hex'

  ----------------------------------------------------------------------