tor-prompt requires the readline module
When compiling Python ourselves several modules (most notably compression) are
unavailable by default. Turns out readline is one of those, so we cannot assume
it is always present...

  ======================================================================
  ERROR: test_running_command
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/system.py", line 1329, in call
      raise OSError('%s returned exit status %i' % (command, exit_status))
  OSError: ['/home/atagar/Python-3.7.0/python', '/home/atagar/Desktop/stem/tor-prompt', '--interface', 1111, '--run', 'GETINFO config-file'] returned exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/interpreter.py", line 36, in test_running_command
      self.assertEqual(expected, _run_prompt('--run', 'GETINFO config-file'))
    File "/home/atagar/Desktop/stem/test/integ/interpreter.py", line 20, in _run_prompt
      return stem.util.system.call([sys.executable, PROMPT_CMD, '--interface', test.runner.CONTROL_PORT] + list(args))
    File "/home/atagar/Desktop/stem/stem/util/system.py", line 1348, in call
      raise CallError(str(exc), ' '.join(command_list), exit_status, runtime, stdout, stderr)
  stem.util.system.CallError: ['/home/atagar/Python-3.7.0/python', '/home/atagar/Desktop/stem/tor-prompt', '--interface', 1111, '--run', 'GETINFO config-file'] returned exit status 1

  ======================================================================
  ERROR: test_running_file
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/stem/util/system.py", line 1329, in call
      raise OSError('%s returned exit status %i' % (command, exit_status))
  OSError: ['/home/atagar/Python-3.7.0/python', '/home/atagar/Desktop/stem/tor-prompt', '--interface', 1111, '--run', '/tmp/test_commands.wmb8rcb8'] returned exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/interpreter.py", line 56, in test_running_file
      self.assertEqual(expected, _run_prompt('--run', tmp.name))
    File "/home/atagar/Desktop/stem/test/integ/interpreter.py", line 20, in _run_prompt
      return stem.util.system.call([sys.executable, PROMPT_CMD, '--interface', test.runner.CONTROL_PORT] + list(args))
    File "/home/atagar/Desktop/stem/stem/util/system.py", line 1348, in call
      raise CallError(str(exc), ' '.join(command_list), exit_status, runtime, stdout, stderr)
  stem.util.system.CallError: ['/home/atagar/Python-3.7.0/python', '/home/atagar/Desktop/stem/tor-prompt', '--interface', 1111, '--run', '/tmp/test_commands.wmb8rcb8'] returned exit status 1