Bad endpoint type within test
Stem 2.x dropped support for tuple endpoints. Guess I haven't run our ONLINE
test target since then...

  ======================================================================
  ERROR: test_using_authorities
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 60, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 75, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/descriptor/remote.py", line 113, in test_using_authorities
      validate = True,
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 408, in __init__
      raise ValueError("Endpoints must be an stem.ORPort or stem.DirPort. '%s' is a %s." % (endpoint, type(endpoint).__name__))
  ValueError: Endpoints must be an stem.ORPort or stem.DirPort. '('128.31.0.39', 9131)' is a tuple.