Fix stem.descriptor.remote vote fetching
Commit a4ecadb broke our ability to download consensus votes...

  https://trac.torproject.org/projects/tor/ticket/30930

  ======================================================================
  ERROR: test_each_getter
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/remote.py", line 286, in test_each_getter
      downloader.get_vote(stem.directory.Authority.from_cache()['moria1'])
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 871, in get_vote
      return self.query(resource, **query_args)
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 999, in query
      return Query(resource, **args)
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 460, in __init__
      self.descriptor_type = _guess_descriptor_type(resource)
    File "/home/atagar/Desktop/stem/stem/descriptor/remote.py", line 1143, in _guess_descriptor_type
      raise ValueError("Unable to determine the descriptor type for '%s'" % resource)
  ValueError: Unable to determine the descriptor type for '/tor/status-vote/current/authority'