Fix x25519_supported AttributeError
Oops, turns out the cryptography module doesn't always supply this method...

  Traceback (most recent call last):
    File "./run_tests.py", line 36, in <module>
      import test.runner
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/runner.py", line 44, in <module>
      import stem.connection
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/connection.py", line 136, in <module>
      import stem.control
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/control.py", line 271, in <module>
      import stem.descriptor.microdescriptor
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/descriptor/__init__.py", line 1544, in <module>
      import stem.descriptor.hidden_service
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/stem/descriptor/hidden_service.py", line 81, in <module>
      X25519_AVAILABLE = backend.x25519_supported()
  AttributeError: 'Backend' object has no attribute 'x25519_supported'