Fix test_repurpose_circuit crash by changing directive in format string
Traceback:
  File "./test/integ/control/controller.py", line 486, in test_repurpose_circuit
    circ = filter(re.compile("^%i " % circ_id).match, circuit_output.splitlines())[0]
TypeError: %d format: a number is required, not str

Also, change to standard variable name "circuit_id.

Signed-off-by: Sean Robinson <seankrobinson@gmail.com>