With python3 tempfile requires bytes input
Another integ test failure that manifests with python 3.6 but oddly not 3.2...

  ======================================================================
  ERROR: test_running_file
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/interpreter.py", line 52, in test_running_file
      tmp.write('GETINFO config-file\nGETINFO version')
    File "/home/atagar/python3.6/lib/python3.6/tempfile.py", line 483, in func_wrapper
      return func(*args, **kwargs)
  TypeError: a bytes-like object is required, not 'str'