Decode cookie path with filesystem encoding first
Oops, I iterated over a set to deduplicate if our filesystem encoding is utf-8
or latin-1. However, there's no harm in decoding twice and doing so
inconsistently broke our unit test because set order is non-deterministic
(so we sometimes decoded our unicode path as latin-1).

  ======================================================================
  FAIL: test_unicode_cookie
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/usr/lib/python3.7/unittest/mock.py", line 1204, in patched
      return func(*args, **keywargs)
    File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/response/protocolinfo.py", line 160, in test_unicode_cookie
      self.assertEqual(EXPECTED_UNICODE_PATH, control_message.cookie_path)
  AssertionError: '/home/user/文档/tor-browser_en-US/Browser/TorBrowser/D[23 chars]okie' != '/home/user/æ\x96\x87æ¡£/tor-browser_en-US/Browser/To[33 chars]okie'
  - /home/user/文档/tor-browser_en-US/Browser/TorBrowser/Data/Tor/control_auth_cookie
  ?            ^^
  + /home/user/æ–‡æ¡£/tor-browser_en-US/Browser/TorBrowser/Data/Tor/control_auth_cookie
  ?            ^^^^^^