Checking for testing prereq of mock 0.8.0
We had a requirement on mock 0.7.0 but it turns out that we're using a 0.8.0
feature too. Spotted this while trying to use ubuntu jaunty's apt-get
version...

Traceback (most recent call last):
  File "./run_tests.py", line 405, in <module>
    main()
  File "./run_tests.py", line 184, in main
    for test_class in test.util.get_unit_tests(args.test_prefix):
  File "/home/atagar/Desktop/stem/test/util.py", line 130, in _get_tests
    module = __import__(module_name)
  File "/home/atagar/Desktop/stem/test/unit/tutorial.py", line 23, in <module>
    class TestTutorial(unittest.TestCase):
  File "/home/atagar/Desktop/stem/test/unit/tutorial.py", line 24, in TestTutorial
    @patch('sys.stdout', new_callable = StringIO.StringIO)
TypeError: patch() got an unexpected keyword argument 'new_callable'