Converting cookie auth token to unicode
Well, this is dumb. Making a formatted string with ascii bytes includes the b''
wrapper in python 3. This broke our authentication calls, making calls like...

AUTHENTICATE b'd55e81eb9c3a1e22a2db919ec2efd22df4aeb88ee0ab3d10e64dbb2450d06921'

Converting the token to unicode to avoid this.

======================================================================
ERROR: test_authenticate_cookie
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/connection/authentication.py", line 400, in _check_auth
    stem.connection.authenticate_cookie(control_socket, auth_arg)
  File "/home/atagar/Desktop/stem/test/data/python3/stem/connection.py", line 604, in authenticate_cookie
    raise CookieAuthRejected(str(auth_response), cookie_path, False, auth_response)
stem.connection.CookieAuthRejected: Invalid hexadecimal encoding.  Maybe you tried a plain text password?  If so, the standard requires that you put it in double quotes.

During handling of the above exception, another exception occurred:

Traceback:
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/connection/authentication.py", line 303, in test_authenticate_cookie
    self._check_auth(auth_type, auth_value)
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/connection/authentication.py", line 411, in _check_auth
    failure_msg = _get_auth_failure_message(auth_type)
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/connection/authentication.py", line 99, in _get_auth_failure_message
    raise ValueError("No methods of authentication. If this is an open socket then auth shouldn't fail.")
ValueError: No methods of authentication. If this is an open socket then auth shouldn't fail.