Don't validate crosscert without cryptography module
Oops, we shouldn't exercise this validation when the cryptography module isn't
present.

	======================================================================
	FAIL: test_cached_descriptor
	----------------------------------------------------------------------
	Traceback (most recent call last):
  	File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 150, in <lambda>
  	  self.method = lambda test: self.result(test)  # method that can be mixed into TestCases
	  File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 220, in result
  	  test.fail(self._result.msg)
	AssertionError: Traceback (most recent call last):
  	File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 168, in _wrapper
    	runner(*args) if args else runner()
  	File "/home/atagar/Desktop/stem/test/integ/descriptor/server_descriptor.py", line 34, in test_cached_descriptor
    	for desc in stem.descriptor.parse_file(descriptor_file, 'server-descriptor 1.0', validate = True):
  	File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 274, in parse_file
    	for desc in parse(descriptor_file):
  	File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 321, in _parse_metrics_file
    	for desc in stem.descriptor.server_descriptor._parse_file(descriptor_file, is_bridge = False, validate = validate, **kwargs):
  	File "/home/atagar/Desktop/stem/stem/descriptor/server_descriptor.py", line 221, in _parse_file
    	yield RelayDescriptor(descriptor_text, validate, annotations, **kwargs)
  	File "/home/atagar/Desktop/stem/stem/descriptor/server_descriptor.py", line 833, in __init__
    	onion_key_crosscert_digest = self._digest_for_signature(self.onion_key, self.onion_key_crosscert)
  	File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 734, in _digest_for_signature
  	  raise ValueError('Generating the signed digest requires the cryptography module')
	ValueError: Generating the signed digest requires the cryptography module