Python3 support for server descriptor signing
While writing it I consciously didn't invest effort into making it compatible.
Now that we've got it working fixing that. Most interesting issue was...

  ======================================================================
  ERROR: test_descriptor_signing
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/unit/descriptor/server_descriptor.py", line 260, in test_descriptor_signing
      RelayDescriptor.create(sign = True)
    File "/home/atagar/Desktop/stem/stem/descriptor/server_descriptor.py", line 873, in create
      return cls(cls.content(attr, exclude, sign, private_signing_key), validate = validate, skip_crypto_validation = not sign)
    File "/home/atagar/Desktop/stem/stem/descriptor/server_descriptor.py", line 865, in content
      signature = base64.b64encode(private_signing_key.sign(content, padding.PKCS1v15(), hashes.SHA1()))
    File "/usr/local/lib/python3.2/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 463, in sign
      algorithm, self, data
    File "/usr/local/lib/python3.2/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 199, in _rsa_sig_sign
      backend.openssl_assert(res > 0)
  TypeError: unorderable types: NoneType() > int()

  ----------------------------------------------------------------------

This was due to one of our no_op mocks.