OrderedDict substitute for older python versions
In d30a628e I simplified the _get_descriptor_components() by using the
collections.OrderedDict builtin. Unforutunately OrderedDict was introduced in
python 2.7, breaking our 2.5 and 2.6 compatability...

======================================================================
ERROR: test_voting_delay
----------------------------------------------------------------------
Traceback:
  File "/home/atagar/Desktop/stem/test/unit/descriptor/networkstatus/document_v3.py", line 359, in test_voting_delay
    document = get_network_status_document_v3({"voting-delay": "12 345"})
  File "/home/atagar/Desktop/stem/test/mocking.py", line 782, in get_network_status_document_v3
    return stem.descriptor.networkstatus.NetworkStatusDocumentV3(desc_content, validate = True)
  File "/home/atagar/Desktop/stem/stem/descriptor/networkstatus.py", line 458, in __init__
    self._header = _DocumentHeader(document_file, validate, default_params)
  File "/home/atagar/Desktop/stem/stem/descriptor/networkstatus.py", line 541, in __init__
    entries = stem.descriptor._get_descriptor_components(content, validate)
  File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 289, in _get_descriptor_components
    entries = collections.OrderedDict()
AttributeError: 'module' object has no attribute 'OrderedDict'

Caught by eoinof on...

https://trac.torproject.org/7244

I'm fixing this by adding an OrderedDict substitute that's under the MIT
license...

http://pypi.python.org/pypi/ordereddict