Fix undefined enum
======================================================================
ERROR: test_encode_decode_certificate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/require.py", line 57, in wrapped
    return func(self, *args, **kwargs)
  File "/home/atagar/Desktop/stem/test/unit/descriptor/certificate.py", line 210, in test_encode_decode_certificate
    my_ed_cert = stem.descriptor.certificate.MyED25519Certificate(cert_type=CertType.HS_V3_DESC_SIGNING_KEY,
AttributeError: 'Enum' object has no attribute 'HS_V3_DESC_SIGNING_KEY'