Test failure due to get_socks_listeners removal
Our deprecated get_socks_listeners() method was removed. Fixing a few tests
that broke when we run our ONLINE target...

  ======================================================================
  ERROR: test_get_streams
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 73, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/require.py", line 73, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1069, in test_get_streams
      socks_listener = controller.get_socks_listeners()[0]
  AttributeError: 'Controller' object has no attribute 'get_socks_listeners'