Unit test broken by get_port() type change
Oops, just ran the integ tests prior to pushing. Type change broke a unit test.

  ======================================================================
  FAIL: test_get_ports
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Python-3.7.0/Lib/unittest/mock.py", line 1191, in patched
      return func(*args, **keywargs)
    File "/home/atagar/Desktop/stem/test/unit/control/controller.py", line 231, in test_get_ports
      self.assertEqual([9050], self.controller.get_ports(Listener.CONTROL))
  AssertionError: [9050] != {9050}

  ----------------------------------------------------------------------