connect() broke Controller's iterator methods
Damn I need to rewrite our connection module. As indicated by the TODO comment,
this method copies some of Synchronous' init. No surprise then that when I
fixed Synchronous' iterators the fix didn't get propagated here.

Caught thanks to toralf noticing that our relay_connections.py example didn't
work...

  % python3.7 relay_connections.py
   0.4.5.0-alpha-dev   uptime: 14:27   flags: none

  Traceback (most recent call last):
    File "relay_connections.py", line 130, in <module>
      main()
    File "relay_connections.py", line 50, in main
      for desc in controller.get_network_statuses():
  TypeError: 'async_generator' object is not iterable