Require online target for server descriptor integ test
Odd, we have both a test_get_server_descriptor and test_get_server_descriptors
(plural) integration test but only the later required the online target. Here
at a coffee shop I got the following so adding this requirement to the other as
well.

  ======================================================================
  ERROR: test_get_server_descriptor
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/require.py", line 58, in wrapped
      return func(self, *args, **kwargs)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1301, in test_get_server_descriptor
      test_relay = self._get_router_status_entry(controller)
    File "/home/atagar/Desktop/stem/test/integ/control/controller.py", line 1489, in _get_router_status_entry
      for desc in controller.get_network_statuses():
    File "/home/atagar/Desktop/stem/stem/control.py", line 482, in wrapped
      for val in func(self, *args, **kwargs):
    File "/home/atagar/Desktop/stem/stem/control.py", line 1979, in get_network_statuses
      raise stem.DescriptorUnavailable('Descriptor information is unavailable, tor might still be downloading it')
  stem.DescriptorUnavailable: Descriptor information is unavailable, tor might still be downloading it