Python 3 compatability for mapaddress test
Quite a few byte vs unicode gotchas. Also, the behavior of indexing into byte
strings changed in python 3 (it provides ints rather than characters).

======================================================================
ERROR: test_mapaddress
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/atagar/Desktop/stem/test/data/python3/test/integ/control/controller.py", line 813, in test_mapaddress
    test.network.negotiate_socks(s, '1.2.1.2', 80)
  File "/home/atagar/Desktop/stem/test/data/python3/test/network.py", line 321, in negotiate_socks
    request = "\x04\x01" + struct.pack("!H", port) + "\x00\x00\x00\x01" + "\x00" + host + "\x00"
TypeError: Can't convert 'bytes' object to str implicitly