Older ssl versions caused test_not_orport to fail
Our integ tests fail on an older system of mine due to lacking tor's version of ssl...

  ======================================================================
  FAIL: test_not_orport
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/integ/client/connection.py", line 34, in test_not_orport
      self.assertRaisesWith(stem.SocketError, "Failed to SSL authenticate to 127.0.0.1:1111. Maybe it isn't an ORPort?", Relay.connect, '127.0.0.1', test.runner.CONTROL_PORT)
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 288, in assertRaisesWith
      return self.assertRaisesRegexp(exc_type, '^%s$' % re.escape(exc_msg), func, *args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/util/test_tools.py", line 298, in assertRaisesRegexp
      return super(original_type, self).assertRaisesRegexp(exc_type, exc_msg, func, *args, **kwargs)
  AssertionError: "^Failed\ to\ SSL\ authenticate\ to\ 127\.0\.0\.1\:1111\.\ Maybe\ it\ isn\'t\ an\ ORPort\?$" does not match "[Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol"

That's fine. This test is supposed to error, just a different message than what
we expected.