Compare exit policy strings in unit tests
Oops, my prior commit made jenkins sad...

	======================================================================
	FAIL: test_get_exit_policy_if_not_relaying
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
  	  return func(*args, **keywargs)
	  File "/srv/jenkins-workspace/workspace/stem-tor-ci/test/unit/control/controller.py", line 247, in test_get_exit_policy_if_not_relaying
  	  self.assertEqual(expected, self.controller.get_exit_policy())
	AssertionError: <stem.exit_policy.ExitPolicy object at 0x7f680846e550> != <stem.exit_policy.ExitPolicy object at 0x7f6808399650>

	----------------------------------------------------------------------

No doubt I'm missing a mock. This isn't gonna fix that, but this should make
the assertion failure more helpful.