Disconnected sockets raise OSErrors
Dropping exception normalization has caused our tests to fail with...

  ======================================================================
  ERROR: test_disconnected_socket
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/response/control_message.py", line 169, in test_disconnected_socket
      self.assertRaises(stem.SocketClosed, stem.socket.recv_message, control_socket_file)
    File "/home/atagar/Python-3.7.0/Lib/unittest/case.py", line 743, in assertRaises
      return context.handle('assertRaises', args, kwargs)
    File "/home/atagar/Python-3.7.0/Lib/unittest/case.py", line 178, in handle
      callable_obj(*args, **kwargs)
    File "/home/atagar/Desktop/stem/stem/socket.py", line 665, in recv_message
      line = control_file.readline()
    File "/home/atagar/Python-3.7.0/Lib/socket.py", line 589, in readinto
      return self._sock.recv_into(b)
  OSError: [Errno 107] Transport endpoint is not connected

Rather than catching socket.error as we used to narrowing this to OSErrors. If
other socket error subclasses come up in practice we'll go back to the parent
class.