Drop use of sys.maxint for descriptor creation
Python 3.x drops sys.maxint...

  https://stackoverflow.com/questions/13795758/what-is-sys-maxint-in-python-3

As such descriptor creation broke our python3 compatibility...

  ======================================================================
  ERROR: test_new_consensus_event
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/response/events.py", line 1005, in test_new_consensus_event
      's': 'Fast Named Running Stable Valid',
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 611, in create
      return cls(cls.content(attr, exclude, sign), validate = validate)
    File "/home/atagar/Desktop/stem/stem/descriptor/router_status_entry.py", line 625, in content
      ('r', '%s p1aag7VwarGxqctS7/fS0y5FU+s oQZFLYe9e4A7bOkWKR7TaNxb0JE %s %s 9001 0' % (_random_nickname(), _random_date(), _random_ipv4_address())),
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 1046, in _random_nickname
      return ('Unnamed%i' % random.randint(0, sys.maxint))[:20]
  AttributeError: 'module' object has no attribute 'maxint'

No big whoop. We were just using it for 'gimme a big random number'. Fixing
this revealed that we also had an off-by-one error with the string truncation.