Only import crypto modules if available
Stem has a soft dependency on the cryptography module. If unavailable we should
gracefully degrade or explicitly error with a message saying that cryptography
is required.

Also, cryptography's ed25519 class is pretty new, so folks will have outdated
module versions for a while...

  ======================================================================
  ERROR: test_for_decrypt
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/Desktop/stem/test/unit/descriptor/hidden_service_v3.py", line 43, in test_for_decrypt
      onion_address="sltib6sxkuxh2scmtuvd5w2g7pahnzkovefxpo4e4ptnkzl5kkq5h2ad.onion"))
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 442, in parse_file
      for desc in parse(descriptor_file):
    File "/home/atagar/Desktop/stem/stem/descriptor/__init__.py", line 545, in _parse_metrics_file
      for desc in stem.descriptor.hidden_service._parse_file(descriptor_file, desc_type, validate = validate, **kwargs):
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 156, in _parse_file
      yield desc_type(bytes.join(b'', descriptor_content), validate, **kwargs)
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 571, in __init__
      plaintext = self.decrypt_descriptor(desc_signing_cert)
    File "/home/atagar/Desktop/stem/stem/descriptor/hidden_service.py", line 579, in decrypt_descriptor
      identity_public_key = stem.descriptor.hsv3_crypto.decode_address(self.onion_address)
    File "/home/atagar/Desktop/stem/stem/descriptor/hsv3_crypto.py", line 30, in decode_address
      from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
  ImportError: No module named ed25519